### PR TITLE
FIX - Test for inconsistent xref for catalog.

### LINKED ISSUE #208: Inconsistent catalog indirect reference and object number
The document catalog is referenced as an indirect object in the /Root key value pair of the trailer. However, this reference does not seem to be cross-checked with the actual object number of the document catalog. Test case T02-01_002 from the ipres test corpus points to object 5 in the trailer /Root entry, however, the document catalog number has been changed to 6. The file cannot be rendered by Adobe Acrobat but JHOVE considers it well-formed and valid.

### PR DESCRIPTION
**Pull request by carlwilson**
- added test for inconsistent object number from xref table;
- added constant for inconsistent catalog number; and
- unit tests and resources for Doc Catalog.
Closes #208

### CODE REVIEW

File: jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java [hunk 1]
```diff
@@ -199,6 +196,7 @@
 	private static final String DICT_KEY_LANG = "Lang";
 	private static final String DICT_KEY_PAGES = "Pages";
 	private static final String DICT_KEY_PAGE_LABELS = "PageLabels";
+    private static final String DICT_KEY_TYPE = "Type";
```
Comment (david-russo) [inline jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java]: Mixed indentation white-space.

File: jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/PdfModuleTest.java [hunk 2]
```diff
@@ -0,0 +1,118 @@
+/**
+ * 
+ */
```
Comment (david-russo) [inline jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/PdfModuleTest.java]: Empty Javadoc.

File: jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/TestUtils.java [hunk 3]
```diff
@@ -0,0 +1,95 @@
+/**
+ * 
+ */
```
Comment (david-russo) [inline jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/TestUtils.java]: Empty Javadoc.

File: jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/TestUtils.java [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+ * @author <a href="mailto:carl@openpreservation.org">Carl Wilson</a>
+ *         <a href="https://github.com/carlwilson">carlwilson AT github</a>
+ * @version 0.1 Created 14 Mar 2018:20:14:19
+ */
+
+public final class TestUtils {
+
+	/**
+	 * 
+	 */
```
Comment (david-russo) [inline jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/TestUtils.java]: Empty Javadoc.

File: jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java [hunk 5]
```diff
@@ -1655,14 +1651,41 @@ protected boolean readDocCatalogDict(RepInfo info)
...
+            // Check that the catalog has a key type and the types value is catalog
+            PdfObject type = _docCatDict.get(DICT_KEY_TYPE);
+            if (type != null && type instanceof PdfSimpleObject) {
+                // If the type key is not null and is a simple object
+                String typeText = ((PdfSimpleObject) type).getStringValue();
+                if (!typeText.equals("Catalog")) {
+                    // If the type key value is not Catalog
+                    info.setWellFormed(false);
+                    info.setMessage(new ErrorMessage(MessageConstants.ERR_DOC_CAT_TYPE_NO_CAT, 0));
+                    info.setMessage(new ErrorMessage(MessageConstants.ERR_DOC_CAT_TYPE_NO_CAT, 0));
```
Comment (david-russo) [inline jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/PdfModule.java]: Duplicate messages?
