### PR TITLE
WAVE: RF64, extended MIME type support, and bug fixes

### LINKED ISSUE #184: Support needed for RF64-formatted WAVs
Example (although can't share the wav file):
```
>java -jar jhove-apps-1.15.0-SNAPSHOT.jar -m WAVE-hul c:\Data\WAVs\Larger_than_2GB_RF64.wav
Jhove (Rel. 1.15.0-SNAPSHOT, 2016-12-02)
 Date: 2017-01-10 16:06:17 GMT
 RepresentationInformation: c:\Data\WAVs\Larger_than_2GB_RF64.wav
  ReportingModule: WAVE-hul, Rel. 1.3 (2007-12-14)
  LastModified: 2014-04-04 03:01:35 BST
  Size: 3371107136
  Format: WAVE
  Status: Not well-formed
  ErrorMessage: Document does not start with RIFF chunk
   Offset: 0
  MIMEtype: audio/x-wave
```

### LINKED ISSUE #278: Invalid character in Chunk ID (WAVE Module)
We have this header for a BWAVE created in Pro Tools: 

      52 49 46 46 BA 5B 56 BF 57 41 56 45 4A 55 4E 4B 5C 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 62 65 78 74 5A 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 72 6F 20 54 6F 6F 6C 73 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 38 67 59 4E 21 76 39 37 68 6B 64 61 61 61 47 6B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 32 30 31 37 2D 30 39 2D 32 00 31 37 3A 32 35 3A 32 32 00 70 99 14 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 66 6D 74 20 28 00 00 00 01 00 02 00 00 77 01 00 00 CA 08 00 06 00 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 6D 69 6E 66 10 00 00 00 AC D3 7D CE 7F 36 D3 01 01 00 00 00 00 00 00 00 65 6C 6D 31 D6 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 64 61 74 61 3E

The resulting message for the whole file is 'Invalid character in Chunk ID' Character 0x00 and Offset 749. While the full file is 3GB, this header is within that range. Pulling it apart chunk-by-chunk then all the offsets seem to be accurate. The offset reported by JHOVE is between the 'fmt' chunk, and 'minf' chunk. 

So I guess we're just looking for a guide on what's throwing JHOVE's offsets off. 

Thanks,
Ross

### PR DESCRIPTION
**Pull request by david-russo**
- Added support for parsing and validating RF64 files
- Made WAVE parser more resilient to unexpected chunk data
- Improved reporting of WAVE codecs in WAVEFORMATEXTENSIBLE files
- Avoids reporting file format and MIME type until signatures have been verified
- Now reports extended MIME type information, e.g. `audio/vnd.wave; codec=1`, as per RFC 2361
- Subformat GUID's are now reported in their standard format, e.g. `00000001-0000-0010-8000-00AA00389B71`, instead of as an array of byte values
- Added check to verify the existence of Data chunks
- Added check to verify that Format chunks appear before Data chunks
- Expanded WAVE example corpora to cover more formats and errors
- Improved truncation detection and reporting
- Fixed erroneous reporting of Cue Point values
- Renamed "Cue" report property to "CuePoints"

Closes #184 and fixes #278.

### CODE REVIEW

**Comment by tledoux** [comment]
Hi, is the requirement of Java 8 mandatory ?
Jhove is a fundation piece of code for preservation ; so asking for Java 8 forces everything on top of it to be in Java 8. 

Maybe a requirement for java 7 would be enough. In any case, a quick survey is needed before going to java 8...

**Comment by david-russo** [comment]
The requirement comes from the use of Java 8's new unsigned-operation methods, such as `Long.compareUnsigned()`. It could be removed if we re-implemented those functions locally, though I'd still encourage a move to Java 8: support from Oracle for 7 [ended in 2015](https://java.com/en/download/faq/java_7.xml), and is [ending in June this year](https://access.redhat.com/articles/1299013) for the OpenJDK. Java 8 has had almost 4 years worth of maintenance releases at this point, so I'd think it should be fairly well supported by now, but I certainly see the prudence in a survey given the infrastructure JHOVE might be embedded in, as you mentioned.

**Comment by david-russo** [comment]
The requirement for Java 8 has now been removed, reverting compatibility to Java 6.

**Comment by tledoux** [comment]
Thanks. Very much appreciated

File: jhove-core/src/main/java/edu/harvard/hul/ois/jhove/RAFInputStream.java [hunk 1]
```diff
@@ -19,106 +21,117 @@
...
         super();
         _raf = raf;
-        fileBufSize = (bufferSize <= 0 ? 65536 : bufferSize);
-        init ();
+        fileBufSize = (bufferSize <= 0 ? DEFAULT_BUFFER_SIZE : bufferSize);
+        init();
     }
 
-    private void init ()
+    private void init()
```
Comment (carlwilson) [inline jhove-core/src/main/java/edu/harvard/hul/ois/jhove/RAFInputStream.java:84]: Super pernickety and I have no good answer but the constructor above is corrected with the open bracket alongside the declaration (correct IMO) but for init just the spacing is corrected. Sorry take that back, mis-read the above and spent too much time recently working through JHOVE's inconsistent spacing / formatting issues.

File: jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java [hunk 2]
```diff
@@ -4355,21 +4355,21 @@ private void writeAESTimeRange (String baseIndent,
...
 	    _writer.println (margn2 + element ("tcf:minutes",
-			       Integer.toString (duration.getMinutes ())));
+			       Long.toString (duration.getMinutes ())));
 	    _writer.println (margn2 + element ("tcf:seconds", 
-			       Integer.toString (duration.getSeconds ())));
-	    _writer.println (margn2 + element 
-                    ("tcf:frames", Integer.toString (duration.getFrames ())));
+			       Long.toString (duration.getSeconds ())));
+	    _writer.println (margn2 + element ("tcf:frames",
+			       Long.toString (duration.getFrames ())));
```
Comment (carlwilson) [inline jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java]: Mixed spacing by the looks

File: jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/TextHandler.java [hunk 3]
```diff
@@ -1073,19 +1073,23 @@ private void writeAESTimeRange (String baseIndent,
...
 	double sr = start.getSampleRate ();
 	if (sr == 1.0) {
 	    sr = _sampleRate;
 	}
 	_writer.println (margn3 + "SampleRate: S" +
 			 Integer.toString ((int) sr));
-	_writer.println (margn3 + "NumberOfSamples: " + 
-			 Integer.toString (start.getSamples ()));
+        _writer.println (margn3 + "NumberOfSamples: " +
+                Long.toString (start.getSamples ()));
```
Comment (carlwilson) [inline jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/TextHandler.java]: Mixed spacing on this and the next four changes from Integer to Long.

File: jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java [hunk 4]
```diff
@@ -4378,7 +4378,7 @@ private void writeAESTimeRange (String baseIndent,
 	    _writer.println (margn2 + elementStart ("tcf:samples",
 						    sampleAttrs));
 	    _writer.println (margn3 + element ("tcf:numberOfSamples",
-			       Integer.toString (duration.getSamples ()) ));
+			       Long.toString (duration.getSamples ()) ));
```
Comment (carlwilson) [inline jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java:4389]: Mixed spacing.

File: jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/FormatChunk.java [hunk 5]
```diff
@@ -108,113 +135,157 @@ public boolean readChunk(RepInfo info) throws IOException {
...
         switch (numChannels) {
             case 2:
-            mapLoc[0] = "LEFT";
-            mapLoc[1] = "RIGHT";
-            break;
-            
+                mapLoc[0] = "LEFT";
+                mapLoc[1] = "RIGHT";
+                break;
+
```
Comment (carlwilson) [inline jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/FormatChunk.java:240]: Mixed spacing.

File: jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/FormatChunk.java [hunk 6]
```diff
@@ -108,113 +135,157 @@ public boolean readChunk(RepInfo info) throws IOException {
...
             // If we get some other number of channels, punt.
             default:
-            for (int i = 0; i < numChannels; i++) {
-                mapLoc[i] = "UNKNOWN";
-            }
+                for (int i = 0; i < numChannels; i++) {
+                    mapLoc[i] = "UNKNOWN";
+                }
```
Comment (carlwilson) [inline jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/FormatChunk.java:245]: Mixed spacing.

**Review by carlwilson — CHANGES_REQUESTED** [review]
We should chat briefly about JHOVE formatting.

File: jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java (hunk 2 above)
Comment (david-russo) [reply jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java]: Oh yeah, the *Handler files are a mess with white-space inconsistencies, even with tabs and spaces on the same line at times, or switching every handful of lines. I originally attempted to fix it, but there was just too much.

The half tabs and half spaces is actually consistent with the code's surrounding lines, which you can see by slowly highlighting line 4370 above.

File: jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/FormatChunk.java (hunk 5 above)
Comment (david-russo) [reply jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/wave/FormatChunk.java:240]: Looks the same to me... Should we not indent switch cases?

File: jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/TextHandler.java (hunk 3 above)
Comment (david-russo) [reply jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/TextHandler.java]: Yeah, I probably should have matched the spacing with the line directly above instead of the line beneath, but this is one of those areas that is already in a sea of inconsistencies.

File: jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java (hunk 4 above)
Comment (david-russo) [reply jhove-core/src/main/java/edu/harvard/hul/ois/jhove/handler/XmlHandler.java:4389]: A pre-existing issue.

**Review by carlwilson — APPROVED** [review]
