### PR TITLE
FIX - PDF module, various processing errors

### LINKED ISSUE #207: PDF version checking not correct
PDF version checking is only carries out against M=1, leading to invalid version entries such as 1.9 being well-formed and valid. Test case T01_002 from the ipres test corpus replaces the valid 1.6 version entry in the header with 1.9. The JHOVE outcome is well-formed and valid, even though version 1.9 does not exist.

### LINKED ISSUE #208: Inconsistent catalog indirect reference and object number
The document catalog is referenced as an indirect object in the /Root key value pair of the trailer. However, this reference does not seem to be cross-checked with the actual object number of the document catalog. Test case T02-01_002 from the ipres test corpus points to object 5 in the trailer /Root entry, however, the document catalog number has been changed to 6. The file cannot be rendered by Adobe Acrobat but JHOVE considers it well-formed and valid.

### LINKED ISSUE #210: Value for /Type in Document Catalog not validated
The document catalog can be found via an indirect reference in the trailer dictionary in key /Root. Per standard, the document catalog must have a /Type key of value /Catalog. T02-01_006 has a trailer pointing to obj 5 as the document catalog. While all other required entries for the Catalog dictionary are in place, the /Type value for the Catalog has been changed from the expected /Catalog to /Font. As a result the file cannot be rendered by Adobe Acrobat but JHOVE considers it well-formed and valid. There should be a consistency check for the indirect reference to the document catalog.

### LINKED ISSUE #211: Indirect refrence to not existing object in page tree node /Kids array results in well-formed and valid
The page tree node includes a key value pair /Kids with an array of indirect references pointing to page leaf nodes or sub page tree nodes of self. If the array contains either only an indirect reference to self or a combination of indirect reference to existing and nonexisting objects, JHOVE recognized the file as being not well-formed. However, when /Kids only contains an indirect reference to a non-existing object, JHOVE flags the file was being well-formed and valid. 
The test case T02-02_004 of the ipres test corpus contains an indirect reference in /Kids pointing to the non existing object 8.

### LINKED ISSUE #212: Value for /Type in Page Tree Node not validated
The Page Tree Node shall be the root of the document’s page tree. The first page tree node can be located via its indirect reference in the document catalog entry for /Pages. As per standard the page tree node must have a /Type key of value /Pages. This is currently not enforced in JHOVE. While the existence of /Type is checked, it’s value is not. In test case T02-02_009 of the ipres test corpus the expected value /Pages has been replaced with /Pagez.

### PR DESCRIPTION
**Pull request by carlwilson**
- added specific exception catches for XRef `ArrayIndexOutOfBoundsException` for page dictionary and page nodes;
- added consistency checked for retrieved XRef object numbers;
- refactored PDF header validation logic and constants to dedicated `PDFHeader` class;
- added test for invalid PDF minor version number when greater than 7;
- dictionary `/Type` key validation for document catalog and page dictionaries;
- `MessageConstants` for new validation conditions;
- unit tests for header, document catalog and page dictionary issues;
- `TestUtils` class provides basic validation testing methods;
- used iPres corpus test files as unit test resources for header, document catalog and page dictionary tests; and
- updated baseline for 1.19.
Combines #317, #318 and #319.
This PR closes #207, closes #208, closes #210, closes #211 and closes #212.

### CODE REVIEW

File: jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeader.java [hunk 1]
```diff
@@ -0,0 +1,184 @@
+/**
+ *
+ */
```
Comment (david-russo) [inline jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeader.java]: Empty Javadoc.

File: jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeader.java [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+	public static final String PDF_SIG_HEADER = "%" + PDF_VER1_HEADER_PREFIX; //$NON-NLS-1$
+	public static final String POSTSCRIPT_HEADER_PREFIX = "!PS-Adobe-"; //$NON-NLS-1$
+	public static final int MAX_VALID_MAJOR_VERSION = 7;
+
+	private final String versionString;
+	private final boolean isPdfACompilant;
+
+	/**
+	 *
+	 */
```
Comment (david-russo) [inline jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeader.java]: Empty Javadoc.

File: jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeader.java [hunk 3]
```diff
@@ -0,0 +1,184 @@
...
+	 *         {@link PdfHeader#MAX_VALID_MAJOR_VERSION}. Otherwise false.
+	 */
+	public boolean isVersionValid() {
+		// Set minor version to one larger than maximum so invalid if parse
+		// fails
+		int minorVersion = MAX_VALID_MAJOR_VERSION + 1;
+		try {
+			minorVersion = getMinorVersion(this.versionString);
+		} catch (NumberFormatException nfe) {
+			// TODO : Do nothing for now, the version number is still invalid.
```
Comment (david-russo) [inline jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeader.java]: Maybe remove the `TODO` here since there's no instructions on what needs to be done differently in the future, and it's a special keyword for many IDEs and programmers to indicate such.

File: jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeader.java [hunk 4]
```diff
@@ -0,0 +1,184 @@
...
+ * @author <a href="mailto:carl@openpreservation.org">Carl Wilson</a>
+ *         <a href="https://github.com/carlwilson">carlwilson AT github</a>
+ * @version 0.1 Created 8 Mar 2018:00:46:39
+ */
+
+public final class PdfHeader {
+	public static final String PDF_VER1_HEADER_PREFIX = "PDF-1."; //$NON-NLS-1$
+	public static final String PDF_SIG_HEADER = "%" + PDF_VER1_HEADER_PREFIX; //$NON-NLS-1$
+	public static final String POSTSCRIPT_HEADER_PREFIX = "!PS-Adobe-"; //$NON-NLS-1$
+	public static final int MAX_VALID_MAJOR_VERSION = 7;
```
Comment (david-russo) [inline jhove-modules/src/main/java/edu/harvard/hul/ois/jhove/module/pdf/PdfHeader.java]: `MAX_VALID_MAJOR_VERSION` looks like it should be `MAX_VALID_MINOR_VERSION`.

File: jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/PageTreeTests.java [hunk 5]
```diff
@@ -0,0 +1,166 @@
+/**
+ * 
+ */
```
Comment (david-russo) [inline jhove-modules/src/test/java/edu/harvard/hul/ois/jhove/module/pdf/PageTreeTests.java:3]: Empty Javadoc.
