### PR TITLE
FIX - JHOVE GUI property display issues

### LINKED ISSUE #558: JHOVE GUI fails to display info. for certain JPEG files
JHOVE 1.24-RC4 fails to display a RepInfo window in the GUI after choosing the JPEG-hul module and attempting to open certain JPEG files. The same files don't exhibit the issue in JHOVE 1.22.1. The command-line interface for 1.24-RC4 also doesn't seem to have trouble parsing the files.

Example file: https://github.com/openpreserve/jhove/blob/rel/jhove-1.22/test-root/corpora/examples/modules/JPEG-hul/20150213_140637.jpg

Windows 7
JRE 1.8 x86

### PR DESCRIPTION
**Pull request by carlwilson**
- added fix to `RepTreeRoot.addToNode()` that ensures `Property` elements are rendered correctly; and
- hack patch for `addArrayMembers()` to ensure that primitive `int[]`s and `long[]`s are converted to `Integer[]`s and `Long[]`s respectively.

Fixes #558 and #559

### CODE REVIEW

File: jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/RepTreeRoot.java [hunk 1]
```diff
@@ -438,11 +439,25 @@ private void addArrayMembers(DefaultMutableTreeNode node, Property p) {
...
 			case LONG: {
-				addToNode(node, (Long[]) pVal);
+				if (pVal instanceof long[]) {
+					Long[] vals = Arrays.stream((long[])pVal) // IntStream
+							.boxed()				// Stream<Integer>
+							.toArray(Long[]::new);
+					addToNode(node, vals);
+				} else {
+					addToNode(node, (Long[]) pVal);
+				}
```
Comment (david-russo) [inline jhove-apps/src/main/java/edu/harvard/hul/ois/jhove/viewer/RepTreeRoot.java:460]: Might the remaining cases not also be subject to this issue, e.g. arrays of float or double primitives?

**Review by david-russo — COMMENTED** [review]
Works for me.
